import Pkg;
Pkg.activate(".")
Pkg.add("Test")
# Pkg.add("Zygote")
# Pkg.add("Flux")
# Pkg.add("Rotations")
# # Pkg.add("JLD2")
# # Pkg.add("Documenter")
# # Pkg.add("Example")
# Pkg.add("DSP")
# # Pkg.add("Makie")
# Pkg.add("GLMakie")
# # Pkg.add("CairoMakie")
# # Pkg.add("FFTW")
